### ISSUE TITLE
Consider downgrading the `setuptools_scm` requirement

### ISSUE THREAD

**Issue by donn** [efabless/cace#58]
Currently, CACE requires setuptools_scm≥8, which is not available in nixpkgs 23.11 (which is the current stable release channel we have pinned for OpenLane.)

I currently get around this by `sed`-ing the version requirement (and it appears to build just fine.)

https://github.com/efabless/openlane2/blob/b46857b7d4ff6afff65d0bbbdd639da364f5ff26/nix/cace.nix#L41

**Comment by mole99** [comment]
There is no particular reason for scm≥8, I will update the dependencies shortly 👍️
