### ISSUE TITLE
Startup behavior

### ISSUE THREAD

**Issue by RTimothyEdwards** [efabless/cace#72]
I previously had two behaviors in CACE that appear to have become lost:

(1) When `cace-gui` is run, if there is no matching project name or no matching .txt or .yml file, then the GUI still pops up, and waits for the user to select a characterization file to load.

(2) Before `cace-gui` brings up the GUI window, all output text is collected in a "messages" variable.  If the GUI comes up successfully, then "messages" is dumped into the console window pane.  If something happens and `cace-gui` dies, then "messages" is dumped to the terminal as the last thing that happens before the program exits (requiring that exceptions be caught and handled gracefully).

Right now, if I start `cace-gui` and (I think) either of the above items happens, then `cace-gui` returns to the terminal prompt with absolutely no indication that anything happened.

**Comment by mole99** [comment]
Sorry about that, I've changed a few things recently and the order in which the functions are called is just wrong!

**Comment by mole99** [comment]
Fixed by #75
